//
//  NDStyleKit.m
//  StoryHop
//
//  Created by Nikki Durkin on 9/18/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "NDStyleKit.h"


@implementation NDStyleKit

#pragma mark Cache

static UIColor* _green = nil;
static UIColor* _blue = nil;
static UIColor* _darkBlue = nil;
static UIColor* _darkGreen = nil;
static UIColor* _red = nil;
static UIColor* _darkRed = nil;
static UIColor* _lightGrey = nil;
static UIColor* _darkGrey = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _green = [UIColor colorWithRed: 0.533 green: 0.753 blue: 0.341 alpha: 1];
    CGFloat greenHSBA[4];
    [_green getHue: &greenHSBA[0] saturation: &greenHSBA[1] brightness: &greenHSBA[2] alpha: &greenHSBA[3]];

    _darkGreen = [UIColor colorWithHue: greenHSBA[0] saturation: greenHSBA[1] brightness: 0.7 alpha: greenHSBA[3]];
    _blue = [UIColor colorWithRed: 0.278 green: 0.627 blue: 0.859 alpha: 1];
    CGFloat blueHSBA[4];
    [_blue getHue: &blueHSBA[0] saturation: &blueHSBA[1] brightness: &blueHSBA[2] alpha: &blueHSBA[3]];

    _darkBlue = [UIColor colorWithHue: blueHSBA[0] saturation: blueHSBA[1] brightness: 0.7 alpha: blueHSBA[3]];
    _red = [UIColor colorWithRed: 0.929 green: 0.443 blue: 0.38 alpha: 1];
    CGFloat redHSBA[4];
    [_red getHue: &redHSBA[0] saturation: &redHSBA[1] brightness: &redHSBA[2] alpha: &redHSBA[3]];

    _darkRed = [UIColor colorWithHue: redHSBA[0] saturation: redHSBA[1] brightness: 0.8 alpha: redHSBA[3]];
    _lightGrey = [UIColor colorWithRed: 0.916 green: 0.916 blue: 0.916 alpha: 1];
    _darkGrey = [UIColor colorWithRed: 0.345 green: 0.349 blue: 0.357 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)green { return _green; }
+ (UIColor*)blue { return _blue; }
+ (UIColor*)darkBlue { return _darkBlue; }
+ (UIColor*)darkGreen { return _darkGreen; }
+ (UIColor*)red { return _red; }
+ (UIColor*)darkRed { return _darkRed; }
+ (UIColor*)lightGrey { return _lightGrey; }
+ (UIColor*)darkGrey { return _darkGrey; }

#pragma mark Drawing Methods

+ (void)drawGreenButtonWithTitle: (NSString*)title isPressed: (BOOL)isPressed;
{
    //// Color Declarations
    UIColor* white = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(5, 5, 110, 31) cornerRadius: 3];
    [NDStyleKit.green setFill];
    [rectangle2Path fill];


    if (isPressed)
    {
        //// greenButtonPressed Drawing
        UIBezierPath* greenButtonPressedPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(5, 5, 110, 31) cornerRadius: 3];
        [NDStyleKit.darkGreen setFill];
        [greenButtonPressedPath fill];
    }


    //// Text Drawing
    CGRect textRect = CGRectMake(14, 12, 93, 16);
    NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    textStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNext-DemiBold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: white, NSParagraphStyleAttributeName: textStyle};

    [title drawInRect: textRect withAttributes: textFontAttributes];
}

+ (void)drawWriteNewStoryIcon;
{
    //// Color Declarations
    UIColor* color1 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Fill-869 Drawing
    UIBezierPath* fill869Path = UIBezierPath.bezierPath;
    [fill869Path moveToPoint: CGPointMake(28.88, 17.62)];
    [fill869Path addCurveToPoint: CGPointMake(29.5, 17) controlPoint1: CGPointMake(28.88, 17.28) controlPoint2: CGPointMake(29.16, 17)];
    [fill869Path addCurveToPoint: CGPointMake(30.12, 17.62) controlPoint1: CGPointMake(29.84, 17) controlPoint2: CGPointMake(30.12, 17.28)];
    [fill869Path addLineToPoint: CGPointMake(30.12, 35.12)];
    [fill869Path addCurveToPoint: CGPointMake(29.5, 35.75) controlPoint1: CGPointMake(30.12, 35.47) controlPoint2: CGPointMake(29.84, 35.75)];
    [fill869Path addLineToPoint: CGPointMake(3.88, 35.75)];
    [fill869Path addCurveToPoint: CGPointMake(3.25, 35.12) controlPoint1: CGPointMake(3.53, 35.75) controlPoint2: CGPointMake(3.25, 35.47)];
    [fill869Path addLineToPoint: CGPointMake(3.25, 7.62)];
    [fill869Path addCurveToPoint: CGPointMake(3.88, 7) controlPoint1: CGPointMake(3.25, 7.28) controlPoint2: CGPointMake(3.53, 7)];
    [fill869Path addLineToPoint: CGPointMake(23.88, 7)];
    [fill869Path addCurveToPoint: CGPointMake(24.5, 7.62) controlPoint1: CGPointMake(24.22, 7) controlPoint2: CGPointMake(24.5, 7.28)];
    [fill869Path addCurveToPoint: CGPointMake(23.88, 8.25) controlPoint1: CGPointMake(24.5, 7.97) controlPoint2: CGPointMake(24.22, 8.25)];
    [fill869Path addLineToPoint: CGPointMake(4.5, 8.25)];
    [fill869Path addLineToPoint: CGPointMake(4.5, 34.5)];
    [fill869Path addLineToPoint: CGPointMake(28.88, 34.5)];
    [fill869Path addLineToPoint: CGPointMake(28.88, 17.62)];
    [fill869Path closePath];
    [fill869Path moveToPoint: CGPointMake(23.32, 18.83)];
    [fill869Path addLineToPoint: CGPointMake(19.25, 20.58)];
    [fill869Path addCurveToPoint: CGPointMake(19, 20.63) controlPoint1: CGPointMake(19.17, 20.61) controlPoint2: CGPointMake(19.08, 20.63)];
    [fill869Path addCurveToPoint: CGPointMake(18.56, 20.44) controlPoint1: CGPointMake(18.84, 20.63) controlPoint2: CGPointMake(18.68, 20.56)];
    [fill869Path addCurveToPoint: CGPointMake(18.42, 19.75) controlPoint1: CGPointMake(18.38, 20.26) controlPoint2: CGPointMake(18.32, 19.99)];
    [fill869Path addLineToPoint: CGPointMake(20.17, 15.68)];
    [fill869Path addCurveToPoint: CGPointMake(20.3, 15.49) controlPoint1: CGPointMake(20.2, 15.61) controlPoint2: CGPointMake(20.25, 15.54)];
    [fill869Path addLineToPoint: CGPointMake(30.04, 5.75)];
    [fill869Path addLineToPoint: CGPointMake(2, 5.75)];
    [fill869Path addLineToPoint: CGPointMake(2, 37)];
    [fill869Path addLineToPoint: CGPointMake(31.38, 37)];
    [fill869Path addLineToPoint: CGPointMake(31.38, 10.84)];
    [fill869Path addLineToPoint: CGPointMake(23.51, 18.7)];
    [fill869Path addCurveToPoint: CGPointMake(23.32, 18.83) controlPoint1: CGPointMake(23.46, 18.75) controlPoint2: CGPointMake(23.39, 18.8)];
    [fill869Path addLineToPoint: CGPointMake(23.32, 18.83)];
    [fill869Path closePath];
    fill869Path.miterLimit = 4;

    fill869Path.usesEvenOddFillRule = YES;

    [color1 setFill];
    [fill869Path fill];


    //// Fill-870 Drawing
    UIBezierPath* fill870Path = UIBezierPath.bezierPath;
    [fill870Path moveToPoint: CGPointMake(21.27, 16.29)];
    [fill870Path addLineToPoint: CGPointMake(20.19, 18.81)];
    [fill870Path addLineToPoint: CGPointMake(22.71, 17.73)];
    [fill870Path addLineToPoint: CGPointMake(34.4, 6.04)];
    [fill870Path addLineToPoint: CGPointMake(32.96, 4.6)];
    [fill870Path addLineToPoint: CGPointMake(21.27, 16.29)];
    [fill870Path closePath];
    fill870Path.miterLimit = 4;

    fill870Path.usesEvenOddFillRule = YES;

    [color1 setFill];
    [fill870Path fill];


    //// Fill-871 Drawing
    UIBezierPath* fill871Path = UIBezierPath.bezierPath;
    [fill871Path moveToPoint: CGPointMake(36.75, 2.98)];
    [fill871Path addCurveToPoint: CGPointMake(35.67, 2.18) controlPoint1: CGPointMake(36.56, 2.53) controlPoint2: CGPointMake(36.09, 2.18)];
    [fill871Path addCurveToPoint: CGPointMake(35.15, 2.41) controlPoint1: CGPointMake(35.48, 2.18) controlPoint2: CGPointMake(35.3, 2.25)];
    [fill871Path addLineToPoint: CGPointMake(33.84, 3.71)];
    [fill871Path addLineToPoint: CGPointMake(35.29, 5.16)];
    [fill871Path addLineToPoint: CGPointMake(36.59, 3.85)];
    [fill871Path addCurveToPoint: CGPointMake(36.75, 2.98) controlPoint1: CGPointMake(36.83, 3.61) controlPoint2: CGPointMake(36.89, 3.31)];
    [fill871Path closePath];
    fill871Path.miterLimit = 4;

    fill871Path.usesEvenOddFillRule = YES;

    [color1 setFill];
    [fill871Path fill];
}

+ (void)drawTrophyIcon;
{
    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 0.809 green: 0.691 blue: 0.481 alpha: 1];

    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(35.11, 15.25)];
    [bezier2Path addCurveToPoint: CGPointMake(32.21, 16.74) controlPoint1: CGPointMake(34.31, 16.06) controlPoint2: CGPointMake(33.35, 16.55)];
    [bezier2Path addCurveToPoint: CGPointMake(34.94, 4.8) controlPoint1: CGPointMake(33.6, 14.14) controlPoint2: CGPointMake(34.65, 10.41)];
    [bezier2Path addLineToPoint: CGPointMake(37.74, 4.8)];
    [bezier2Path addCurveToPoint: CGPointMake(35.11, 15.25) controlPoint1: CGPointMake(37.77, 7.04) controlPoint2: CGPointMake(37.79, 12.53)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(25.26, 9.48)];
    [bezier2Path addLineToPoint: CGPointMake(22.27, 11.88)];
    [bezier2Path addLineToPoint: CGPointMake(23.47, 15.47)];
    [bezier2Path addCurveToPoint: CGPointMake(23.35, 15.83) controlPoint1: CGPointMake(23.51, 15.6) controlPoint2: CGPointMake(23.46, 15.75)];
    [bezier2Path addCurveToPoint: CGPointMake(23.17, 15.88) controlPoint1: CGPointMake(23.29, 15.86) controlPoint2: CGPointMake(23.23, 15.88)];
    [bezier2Path addCurveToPoint: CGPointMake(22.97, 15.81) controlPoint1: CGPointMake(23.1, 15.88) controlPoint2: CGPointMake(23.03, 15.86)];
    [bezier2Path addLineToPoint: CGPointMake(20, 13.44)];
    [bezier2Path addLineToPoint: CGPointMake(17.03, 15.81)];
    [bezier2Path addCurveToPoint: CGPointMake(16.65, 15.83) controlPoint1: CGPointMake(16.92, 15.9) controlPoint2: CGPointMake(16.77, 15.91)];
    [bezier2Path addCurveToPoint: CGPointMake(16.53, 15.47) controlPoint1: CGPointMake(16.54, 15.75) controlPoint2: CGPointMake(16.49, 15.6)];
    [bezier2Path addLineToPoint: CGPointMake(17.73, 11.88)];
    [bezier2Path addLineToPoint: CGPointMake(14.74, 9.48)];
    [bezier2Path addCurveToPoint: CGPointMake(14.63, 9.13) controlPoint1: CGPointMake(14.63, 9.4) controlPoint2: CGPointMake(14.59, 9.26)];
    [bezier2Path addCurveToPoint: CGPointMake(14.93, 8.92) controlPoint1: CGPointMake(14.68, 9) controlPoint2: CGPointMake(14.8, 8.92)];
    [bezier2Path addLineToPoint: CGPointMake(18.53, 8.92)];
    [bezier2Path addLineToPoint: CGPointMake(19.66, 6.3)];
    [bezier2Path addCurveToPoint: CGPointMake(19.95, 6.11) controlPoint1: CGPointMake(19.71, 6.19) controlPoint2: CGPointMake(19.83, 6.11)];
    [bezier2Path addCurveToPoint: CGPointMake(20.24, 6.29) controlPoint1: CGPointMake(20.09, 6.1) controlPoint2: CGPointMake(20.19, 6.18)];
    [bezier2Path addLineToPoint: CGPointMake(21.47, 8.92)];
    [bezier2Path addLineToPoint: CGPointMake(25.07, 8.92)];
    [bezier2Path addCurveToPoint: CGPointMake(25.37, 9.13) controlPoint1: CGPointMake(25.2, 8.92) controlPoint2: CGPointMake(25.32, 9)];
    [bezier2Path addCurveToPoint: CGPointMake(25.26, 9.48) controlPoint1: CGPointMake(25.41, 9.26) controlPoint2: CGPointMake(25.37, 9.4)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(4.76, 15.25)];
    [bezier2Path addCurveToPoint: CGPointMake(2.26, 4.83) controlPoint1: CGPointMake(2.15, 12.6) controlPoint2: CGPointMake(2.23, 7.35)];
    [bezier2Path addCurveToPoint: CGPointMake(2.26, 4.8) controlPoint1: CGPointMake(2.26, 4.82) controlPoint2: CGPointMake(2.26, 4.81)];
    [bezier2Path addLineToPoint: CGPointMake(5.08, 4.8)];
    [bezier2Path addCurveToPoint: CGPointMake(7.77, 16.75) controlPoint1: CGPointMake(5.36, 10.41) controlPoint2: CGPointMake(6.4, 14.14)];
    [bezier2Path addCurveToPoint: CGPointMake(4.76, 15.25) controlPoint1: CGPointMake(6.56, 16.56) controlPoint2: CGPointMake(5.57, 16.07)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(39, 4.64)];
    [bezier2Path addCurveToPoint: CGPointMake(39, 4.17) controlPoint1: CGPointMake(39, 4.45) controlPoint2: CGPointMake(39, 4.29)];
    [bezier2Path addCurveToPoint: CGPointMake(38.37, 3.53) controlPoint1: CGPointMake(39, 3.82) controlPoint2: CGPointMake(38.72, 3.53)];
    [bezier2Path addLineToPoint: CGPointMake(34.99, 3.53)];
    [bezier2Path addCurveToPoint: CGPointMake(35.02, 1.63) controlPoint1: CGPointMake(35.01, 2.92) controlPoint2: CGPointMake(35.02, 2.29)];
    [bezier2Path addCurveToPoint: CGPointMake(34.38, 1) controlPoint1: CGPointMake(35.02, 1.28) controlPoint2: CGPointMake(34.73, 1)];
    [bezier2Path addLineToPoint: CGPointMake(5.64, 1)];
    [bezier2Path addCurveToPoint: CGPointMake(5, 1.63) controlPoint1: CGPointMake(5.29, 1) controlPoint2: CGPointMake(5, 1.28)];
    [bezier2Path addCurveToPoint: CGPointMake(5.03, 3.53) controlPoint1: CGPointMake(5, 2.29) controlPoint2: CGPointMake(5.02, 2.92)];
    [bezier2Path addLineToPoint: CGPointMake(1.63, 3.53)];
    [bezier2Path addCurveToPoint: CGPointMake(1, 4.17) controlPoint1: CGPointMake(1.28, 3.53) controlPoint2: CGPointMake(1, 3.82)];
    [bezier2Path addCurveToPoint: CGPointMake(0.99, 4.81) controlPoint1: CGPointMake(1, 4.35) controlPoint2: CGPointMake(1, 4.57)];
    [bezier2Path addCurveToPoint: CGPointMake(3.86, 16.14) controlPoint1: CGPointMake(0.96, 7.51) controlPoint2: CGPointMake(0.88, 13.12)];
    [bezier2Path addCurveToPoint: CGPointMake(8.57, 18.09) controlPoint1: CGPointMake(5.07, 17.36) controlPoint2: CGPointMake(6.66, 18.01)];
    [bezier2Path addCurveToPoint: CGPointMake(14.05, 22.89) controlPoint1: CGPointMake(10.27, 20.61) controlPoint2: CGPointMake(12.3, 21.84)];
    [bezier2Path addCurveToPoint: CGPointMake(17.72, 27.97) controlPoint1: CGPointMake(16.26, 24.22) controlPoint2: CGPointMake(17.72, 25.1)];
    [bezier2Path addCurveToPoint: CGPointMake(11.77, 34.57) controlPoint1: CGPointMake(17.63, 33.52) controlPoint2: CGPointMake(15.55, 34.57)];
    [bezier2Path addCurveToPoint: CGPointMake(11.13, 35.2) controlPoint1: CGPointMake(11.42, 34.57) controlPoint2: CGPointMake(11.13, 34.85)];
    [bezier2Path addLineToPoint: CGPointMake(11.13, 38.37)];
    [bezier2Path addCurveToPoint: CGPointMake(11.77, 39) controlPoint1: CGPointMake(11.13, 38.72) controlPoint2: CGPointMake(11.42, 39)];
    [bezier2Path addLineToPoint: CGPointMake(28.23, 39)];
    [bezier2Path addCurveToPoint: CGPointMake(28.87, 38.37) controlPoint1: CGPointMake(28.58, 39) controlPoint2: CGPointMake(28.87, 38.72)];
    [bezier2Path addLineToPoint: CGPointMake(28.87, 35.2)];
    [bezier2Path addCurveToPoint: CGPointMake(28.23, 34.57) controlPoint1: CGPointMake(28.87, 34.85) controlPoint2: CGPointMake(28.58, 34.57)];
    [bezier2Path addCurveToPoint: CGPointMake(22.19, 27.99) controlPoint1: CGPointMake(24.11, 34.57) controlPoint2: CGPointMake(22.19, 32.48)];
    [bezier2Path addCurveToPoint: CGPointMake(25.91, 22.85) controlPoint1: CGPointMake(22.19, 25.09) controlPoint2: CGPointMake(23.67, 24.2)];
    [bezier2Path addCurveToPoint: CGPointMake(31.39, 18.09) controlPoint1: CGPointMake(27.65, 21.81) controlPoint2: CGPointMake(29.68, 20.58)];
    [bezier2Path addCurveToPoint: CGPointMake(36.01, 16.14) controlPoint1: CGPointMake(33.25, 18.01) controlPoint2: CGPointMake(34.8, 17.36)];
    [bezier2Path addCurveToPoint: CGPointMake(39, 4.64) controlPoint1: CGPointMake(39.12, 12.98) controlPoint2: CGPointMake(39.04, 6.92)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    bezier2Path.usesEvenOddFillRule = YES;

    [color3 setFill];
    [bezier2Path fill];
}

+ (void)drawStarIcon;
{
    //// Color Declarations
    UIColor* color5 = [UIColor colorWithRed: 0.809 green: 0.691 blue: 0.481 alpha: 1];

    //// Page-1
    {
        //// Main-activity-screen
        {
            //// Scores-header
            {
                //// Stars-2
                {
                    //// star Drawing
                    UIBezierPath* starPath = UIBezierPath.bezierPath;
                    [starPath moveToPoint: CGPointMake(27.33, 13.69)];
                    [starPath addCurveToPoint: CGPointMake(24.79, 11.89) controlPoint1: CGPointMake(26.17, 13.68) controlPoint2: CGPointMake(25.18, 12.93)];
                    [starPath addCurveToPoint: CGPointMake(24.71, 11.65) controlPoint1: CGPointMake(24.76, 11.81) controlPoint2: CGPointMake(24.73, 11.73)];
                    [starPath addLineToPoint: CGPointMake(21.75, 2.39)];
                    [starPath addLineToPoint: CGPointMake(21.68, 2.16)];
                    [starPath addCurveToPoint: CGPointMake(20, 1) controlPoint1: CGPointMake(21.41, 1.48) controlPoint2: CGPointMake(20.76, 1)];
                    [starPath addCurveToPoint: CGPointMake(18.27, 2.29) controlPoint1: CGPointMake(19.19, 1) controlPoint2: CGPointMake(18.5, 1.54)];
                    [starPath addLineToPoint: CGPointMake(15.28, 11.61)];
                    [starPath addCurveToPoint: CGPointMake(15.18, 11.91) controlPoint1: CGPointMake(15.25, 11.72) controlPoint2: CGPointMake(15.22, 11.82)];
                    [starPath addCurveToPoint: CGPointMake(12.65, 13.68) controlPoint1: CGPointMake(14.79, 12.95) controlPoint2: CGPointMake(13.8, 13.68)];
                    [starPath addLineToPoint: CGPointMake(2.55, 13.69)];
                    [starPath addCurveToPoint: CGPointMake(1, 15.52) controlPoint1: CGPointMake(1.67, 13.82) controlPoint2: CGPointMake(1, 14.59)];
                    [starPath addCurveToPoint: CGPointMake(1.71, 16.98) controlPoint1: CGPointMake(1, 16.12) controlPoint2: CGPointMake(1.28, 16.64)];
                    [starPath addCurveToPoint: CGPointMake(9.64, 22.86) controlPoint1: CGPointMake(1.74, 17) controlPoint2: CGPointMake(9.64, 22.86)];
                    [starPath addCurveToPoint: CGPointMake(10.83, 25.14) controlPoint1: CGPointMake(10.35, 23.35) controlPoint2: CGPointMake(10.83, 24.19)];
                    [starPath addCurveToPoint: CGPointMake(10.76, 25.77) controlPoint1: CGPointMake(10.83, 25.36) controlPoint2: CGPointMake(10.81, 25.57)];
                    [starPath addCurveToPoint: CGPointMake(10.61, 26.23) controlPoint1: CGPointMake(10.72, 25.93) controlPoint2: CGPointMake(10.67, 26.08)];
                    [starPath addLineToPoint: CGPointMake(7.64, 35.53)];
                    [starPath addCurveToPoint: CGPointMake(7.53, 36.16) controlPoint1: CGPointMake(7.55, 35.8) controlPoint2: CGPointMake(7.53, 35.98)];
                    [starPath addCurveToPoint: CGPointMake(9.33, 38) controlPoint1: CGPointMake(7.53, 37.18) controlPoint2: CGPointMake(8.34, 38)];
                    [starPath addCurveToPoint: CGPointMake(10.24, 37.76) controlPoint1: CGPointMake(9.66, 38) controlPoint2: CGPointMake(9.97, 37.91)];
                    [starPath addLineToPoint: CGPointMake(10.55, 37.53)];
                    [starPath addCurveToPoint: CGPointMake(18.33, 31.77) controlPoint1: CGPointMake(10.55, 37.52) controlPoint2: CGPointMake(18.33, 31.77)];
                    [starPath addCurveToPoint: CGPointMake(18.5, 31.64) controlPoint1: CGPointMake(18.39, 31.73) controlPoint2: CGPointMake(18.45, 31.68)];
                    [starPath addCurveToPoint: CGPointMake(20, 31.19) controlPoint1: CGPointMake(18.93, 31.35) controlPoint2: CGPointMake(19.45, 31.19)];
                    [starPath addCurveToPoint: CGPointMake(21.45, 31.62) controlPoint1: CGPointMake(20.53, 31.19) controlPoint2: CGPointMake(21.03, 31.34)];
                    [starPath addCurveToPoint: CGPointMake(21.72, 31.82) controlPoint1: CGPointMake(21.55, 31.68) controlPoint2: CGPointMake(21.64, 31.74)];
                    [starPath addCurveToPoint: CGPointMake(29.47, 37.55) controlPoint1: CGPointMake(21.73, 31.82) controlPoint2: CGPointMake(29.47, 37.55)];
                    [starPath addLineToPoint: CGPointMake(29.69, 37.71)];
                    [starPath addCurveToPoint: CGPointMake(30.64, 37.99) controlPoint1: CGPointMake(29.97, 37.89) controlPoint2: CGPointMake(30.29, 37.99)];
                    [starPath addCurveToPoint: CGPointMake(32.44, 36.15) controlPoint1: CGPointMake(31.63, 37.99) controlPoint2: CGPointMake(32.44, 37.16)];
                    [starPath addCurveToPoint: CGPointMake(32.36, 35.6) controlPoint1: CGPointMake(32.44, 35.96) controlPoint2: CGPointMake(32.42, 35.77)];
                    [starPath addCurveToPoint: CGPointMake(29.34, 26.18) controlPoint1: CGPointMake(32.35, 35.57) controlPoint2: CGPointMake(29.34, 26.18)];
                    [starPath addCurveToPoint: CGPointMake(29.23, 25.81) controlPoint1: CGPointMake(29.3, 26.06) controlPoint2: CGPointMake(29.26, 25.93)];
                    [starPath addCurveToPoint: CGPointMake(29.14, 25.14) controlPoint1: CGPointMake(29.17, 25.59) controlPoint2: CGPointMake(29.14, 25.37)];
                    [starPath addCurveToPoint: CGPointMake(30.17, 22.98) controlPoint1: CGPointMake(29.14, 24.27) controlPoint2: CGPointMake(29.54, 23.49)];
                    [starPath addCurveToPoint: CGPointMake(30.37, 22.83) controlPoint1: CGPointMake(30.23, 22.93) controlPoint2: CGPointMake(30.3, 22.88)];
                    [starPath addLineToPoint: CGPointMake(38.13, 17.09)];
                    [starPath addLineToPoint: CGPointMake(38.37, 16.92)];
                    [starPath addCurveToPoint: CGPointMake(39, 15.52) controlPoint1: CGPointMake(38.76, 16.58) controlPoint2: CGPointMake(39, 16.08)];
                    [starPath addCurveToPoint: CGPointMake(37.42, 13.69) controlPoint1: CGPointMake(39, 14.58) controlPoint2: CGPointMake(38.31, 13.81)];
                    [starPath addLineToPoint: CGPointMake(27.33, 13.69)];
                    [starPath closePath];
                    starPath.miterLimit = 4;

                    starPath.usesEvenOddFillRule = YES;

                    [color5 setFill];
                    [starPath fill];
                }
            }
        }
    }
}

@end
