//
//  NDStyleKit.h
//  StoryHop
//
//  Created by Nikki Durkin on 9/18/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface NDStyleKit : NSObject

// Colors
+ (UIColor*)green;
+ (UIColor*)blue;
+ (UIColor*)darkBlue;
+ (UIColor*)darkGreen;
+ (UIColor*)red;
+ (UIColor*)darkRed;
+ (UIColor*)lightGrey;
+ (UIColor*)darkGrey;

// Drawing Methods
+ (void)drawGreenButtonWithTitle: (NSString*)title isPressed: (BOOL)isPressed;
+ (void)drawWriteNewStoryIcon;
+ (void)drawTrophyIcon;
+ (void)drawStarIcon;

@end
